---
apiVersion: v1
kind: Service
metadata:
  name: sparta-app-svc-2
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 30002           # This is the port your clients will use.
      targetPort: 3000       # This is the port your application is running on.
  selector:
    app: sparta-app-2        # Label to match service to deployment
  type: LoadBalancer