# second-app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: second-app-service
spec:
  type: LoadBalancer
  selector:
    app: second-app
  ports:
  - port: 9000
    targetPort: 80
    nodePort: 30002
